import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { useNavigate } from 'react-router-dom';
import Verse from './Verse';
import { useBibleStore } from '../store';

vi.mock('react-router-dom', async () => {
  const actual = await vi.importActual<
    typeof import('react-router-dom')
  >('react-router-dom');
  return { ...actual, useNavigate: vi.fn() };
});

const mockNavigate = vi.fn();
const mockSetActiveVerses = vi.fn();
const initialStoreState = useBibleStore.getState();

// Mock scrollIntoView
window.HTMLElement.prototype.scrollIntoView = vi.fn();

describe('Verse Component', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    (useNavigate as ReturnType<typeof vi.fn>).mockReturnValue(mockNavigate);
    useBibleStore.setState({
      ...initialStoreState,
      activeVerses: [],
      setActiveVerses: mockSetActiveVerses,
    });
  });

  it('should render the verse number and text', () => {
    render(<Verse verse={1} text="In the beginning..." />);
    expect(screen.getByText('1')).toBeInTheDocument();
    expect(screen.getByText('In the beginning...')).toBeInTheDocument();
  });

  it('should call setActiveVerses to add the verse when clicked', async () => {
    render(<Verse verse={5} text="And God called the light Day..." />);

    const verseElement = screen.getByText('5').parentElement;
    if (!verseElement) throw new Error('Verse element not found');
    await userEvent.click(verseElement);

    expect(mockSetActiveVerses).toHaveBeenCalledWith([5]);
  });

  it('should call setActiveVerses to remove the verse when an active verse is clicked', async () => {
    // Set initial state to have verse 5 active
    useBibleStore.setState({ activeVerses: [5], setActiveVerses: mockSetActiveVerses });

    render(<Verse verse={5} text="And God called the light Day..." />);

    const verseElement = screen.getByText('5').parentElement;
    if (!verseElement) throw new Error('Verse element not found');
    await userEvent.click(verseElement);

    // Should be called with an empty array
    expect(mockSetActiveVerses).toHaveBeenCalledWith([]);
  });

  it('should have the active class and scroll into view when active', () => {
    useBibleStore.setState({ activeVerses: [10], setActiveVerses: mockSetActiveVerses });

    render(<Verse verse={10} text="And God saw that it was good." />);

    const verseElement = screen.getByText('10').parentElement;
    if (!verseElement) throw new Error('Verse element not found');
    // The class name is generated by Mantine, so we check for the presence of the class
    // rather than the exact name.
    expect(verseElement).toHaveAttribute('data-active', 'true');
    expect(window.HTMLElement.prototype.scrollIntoView).toHaveBeenCalledWith({
      block: 'center',
      behavior: 'smooth',
    });
  });

  it('should not have the active class when not active', () => {
    render(<Verse verse={1} text="In the beginning..." />);
    const verseElement = screen.getByText('1').parentElement;
    if (!verseElement) throw new Error('Verse element not found');
    expect(verseElement.className).not.toContain('linkActive');
  });
});
